### ISSUE TITLE
Why not to use the async() method?

### ISSUE THREAD

**Issue by leodido** [basic-web-components/basic-aspect#1]
Here [basic-aspect#L86-L92](https://github.com/basic-web-components/basic-aspect/blob/develop/basic-aspect.html#L86-L92), for example, you could use the **async()** method of **Polymer.Base** to run the callback at microtask timing (i.e. before paint).

``` javascript
this.async(
  function() {
    childAspect = this._firstChildAspect();
    if (childAspect) {
      this.assimilate(childAspect);
    }
  }.bind(this)
);
```

Implementation details [here](https://github.com/Polymer/polymer/blob/master/src/lib/async.html).

I could submit a PR, in the case you agree.

**Comment by JanMiksovsky** [comment]
Good idea. Thanks for the suggestion.

I've checked in [4d4afa](https://github.com/basic-web-components/basic-web-components/commit/4d4afa75cd3c677edac5d0d746068e2e7a80e1e6) to try this out. Unit tests pass, and a spot check of some components looks okay, so let's see if this works in practice.

Looking over the code base, most of the other uses of setTimeout really do want to wait for a repaint. But at least one (in basic-item-selection) may be worth looking at.

Note that basic-aspect's use of setTimeout/async is really a hack here. There's an underlying timing problem in which someone may try to set an aspect's target to another component that hasn't yet been upgraded. I'm not sure if there's a better way to solve the underlying problem.

BTW, we haven't had a chance to really document what aspects are, or the related concept of collectives. We're working on documentation. In the meantime, if you're interested in learning more about why we've done things this way, we have a [presentation](https://docs.google.com/presentation/d/1tTdLanKKbIE5t3PTjtbaXsau2DAMn4EN9wQI2Ri81A8/edit?usp=sharing) that looks at the topic. Please let us know if you have comments.

Oh, for future issues/PRs, it's best to work against the consolidated [basic-web-components](https://github.com/basic-web-components/basic-web-components/) repository. The individual components repos like this one for basic-aspect here are really just for bower distribution.

**Comment by leodido** [comment]
Perfect Jan! And thanks for the pointer to collectives' documentation. I have just started to explorate basic-web-components, with positive impressions.
